### ISSUE TITLE
missing CSS?

### ISSUE THREAD

**Issue by ArdenKirkland** [DBinaghi/plugin-ClickableLinksPlus#1]
Hi! I'm getting this error when trying to use this: 
InvalidArgumentException
Could not find file css/clickable_links_plus.css

Any ideas on how to fix this? Thanks so much for making this available!

**Comment by DBinaghi** [comment]
Hi.
Thanks for your comment.
Reason for the error: I forgot to add two directories when uploading the code :-)

How to fix it: just install the new release.

Regards.
